import { Link } from 'react-router-dom';
import { FileText, ShieldCheck, Lock, Users, Tv, CreditCard } from 'lucide-react';

export default function Policies() {
  return (
    <div className="min-h-screen bg-[#050505] text-[#ededed] font-sans selection:bg-[#1800ad] selection:text-white">
      
      {/* Minimal Navbar */}
  

      {/* Docs Layout */}
      <main className="pt-32 pb-20 px-6 max-w-7xl mx-auto flex flex-col md:flex-row gap-12">
        
        {/* Sticky Sidebar */}
        <aside className="md:w-64 flex-shrink-0">
          <div className="sticky top-32 flex flex-col gap-4">
            <h4 className="text-xs font-bold text-white uppercase tracking-widest mb-2">Legal Hub</h4>
            <a href="#terms" className="text-sm font-medium text-[#888] hover:text-white transition-colors">Terms of Service</a>
            <a href="#privacy-uk" className="text-sm font-medium text-[#888] hover:text-white transition-colors">UK & EU Privacy Policy</a>
            <a href="#privacy-us" className="text-sm font-medium text-[#888] hover:text-white transition-colors">US Privacy Policy</a>
            <a href="#dmca" className="text-sm font-medium text-[#888] hover:text-white transition-colors">DMCA & Copyright</a>
            <a href="#community" className="text-sm font-medium text-[#888] hover:text-white transition-colors">Community Guidelines</a>
            <a href="#mesh-tv" className="text-sm font-medium text-[#888] hover:text-white transition-colors">Mesh TV Terms of Use</a>
            <a href="#subscriptions" className="text-sm font-medium text-[#888] hover:text-white transition-colors">Mesh+ Subscriptions</a>
            <a href="#MeshAI" className="text-sm font-medium text-[#888] hover:text-white transition-colors">Mesh AI Policies</a>
            
            <div className="mt-8 p-4 rounded-xl bg-white/5 border border-white/10">
              <h4 className="text-xs font-bold text-white uppercase mb-2">Need Legal Help?</h4>
              <p className="text-xs text-[#888] mb-3">Questions regarding terms, privacy, or data requests?</p>
              <a href="mailto:Legal@meshservicesuk.com" className="text-xs text-[#3b1df2] font-bold hover:underline block mb-1">
                UK/EU: Legal@meshservicesuk.com
              </a>
              <a href="mailto:meshuslegal@meshservicesuk.info" className="text-xs text-[#3b1df2] font-bold hover:underline block">
                US: meshuslegal@meshservicesuk.info
              </a>
            </div>
          </div>
        </aside>

        {/* Content Area */}
        <div className="flex-1 max-w-3xl">
          <h1 className="text-4xl font-bold tracking-tight text-white mb-4">Platform Policies & Legal Documentation</h1>
          <p className="text-[#888] mb-12">Updated September 2026</p>

          {/* Section: Terms of Service */}
          <section id="terms" className="mb-16 scroll-mt-32">
            <div className="flex items-center gap-2 mb-6 border-b border-white/10 pb-4">
              <FileText className="w-5 h-5 text-[#3b1df2]" />
              <h2 className="text-2xl font-bold text-white">Terms of Service</h2>
            </div>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-2">1. Welcome to Mesh</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Welcome to Mesh Services ("Mesh", "we", "us", or "our"). These Terms of Service govern your access to and use of the Mesh ecosystem, including community servers, peer-to-peer voice calls, direct messaging, Mesh Music, and Mesh TV. By creating an account or using Mesh, you agree to these Terms.
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">2. Strict Age Requirements (18+)</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Mesh is strictly intended for users 18 years of age and older. Age-verification systems are utilized during onboarding to restrict access to anyone under 18. If you are under 18, you are not permitted to register an account or access the platform.
            </p>
            
            <h3 className="text-lg font-bold text-white mt-6 mb-2">3. Mesh Creator Terms (Music & TV)</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              If you upload audio ("Mesh Music") or video ("Mesh TV") content to our infrastructure:
            </p>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Ownership:</strong> You retain full ownership of your intellectual property. By uploading, you grant Mesh a non-exclusive license to host, stream, and display your media across our platform.</li>
              <li><strong className="text-white">Royalties & Payouts:</strong> Eligible creators receive payouts generated by playback history and subscription pools processed via Stripe Billing. Payout and financial records are maintained for 7 years for compliance.</li>
              <li><strong className="text-white">Warranties:</strong> You guarantee that you possess all legal rights, licenses, and clearances for uploaded media. Unauthorized uploads or copyrighted infringements are strictly prohibited.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">4. Acceptable Use</h3>
            <p className="text-[#888] leading-relaxed mb-4">You agree not to use Mesh to:</p>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li>Violate applicable regional, national, or international laws.</li>
              <li>Attempt to reverse-engineer, exploit, or disrupt Mesh infrastructure or Supabase databases.</li>
              <li>Harass, stalk, dox, or transmit malicious code.</li>
            </ul>
          </section>

          {/* Section: UK & EU Privacy Policy */}
          <section id="privacy-uk" className="mb-16 scroll-mt-32">
            <div className="flex items-center gap-2 mb-6 border-b border-white/10 pb-4">
              <ShieldCheck className="w-5 h-5 text-[#3b1df2]" />
              <h2 className="text-2xl font-bold text-white">UK & EU Privacy Policy</h2>
            </div>
            <p className="text-xs text-[#888] uppercase tracking-wider mb-6">Effective Date: 4/09/2026</p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">1. Who We Are</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Mesh Services UK and EU is operated by Dylan Scully trading as "Mesh," United Kingdom. Contact us about privacy at Legal@meshservicesuk.com. Our ICO Registration Number is ZC218381.
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">2. What Mesh Is</h3>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Servers:</strong> Community spaces with text channels, similar to Discord.</li>
              <li><strong className="text-white">Voice calls:</strong> Real-time voice, connected peer-to-peer using WebRTC.</li>
              <li><strong className="text-white">Direct messages:</strong> Private one-to-one and group messaging.</li>
              <li><strong className="text-white">Mesh Music:</strong> A hub where indie artists upload and stream music, with royalty payouts.</li>
              <li><strong className="text-white">Mesh TV:</strong> A platform for indie studios to upload and stream video content.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">3. Information Collection & Lawful Basis</h3>
            <div className="overflow-x-auto mb-6">
              <table className="w-full text-left text-xs border border-white/10 rounded-lg">
                <thead className="bg-white/5 text-white uppercase font-bold border-b border-white/10">
                  <tr>
                    <th className="p-3">Data Category</th>
                    <th className="p-3">Purpose</th>
                    <th className="p-3">Lawful Basis</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5 text-[#888]">
                  <tr>
                    <td className="p-3 font-semibold text-white">Email, username, hashed password</td>
                    <td className="p-3">Create and secure your account</td>
                    <td className="p-3">Contract</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-white">Server membership, roles, text channel messages</td>
                    <td className="p-3">Operate servers and communities</td>
                    <td className="p-3">Contract</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-white">Direct messages (content)</td>
                    <td className="p-3">Deliver private messages</td>
                    <td className="p-3">Contract</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-white">Call signaling data (who called whom, when, duration)</td>
                    <td className="p-3">Connect voice calls</td>
                    <td className="p-3">Contract</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-white">Call audio itself</td>
                    <td className="p-3">Not collected. WebRTC connects devices directly; Mesh's servers help set up the connection but do not receive, transmit through, record, or store the audio.</td>
                    <td className="p-3">N/A</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-white">Music/video play history</td>
                    <td className="p-3">Calculate creator royalties; power recommendations</td>
                    <td className="p-3">Contract (royalties) / Legitimate interests (recommendations)</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-white">Uploaded music, video, and metadata</td>
                    <td className="p-3">Host and stream creator content</td>
                    <td className="p-3">Contract</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-white">App telemetry</td>
                    <td className="p-3">Diagnose issues, improve reliability</td>
                    <td className="p-3">Legitimate interests, or consent where required</td>
                  </tr>
                  <tr>
                    <td className="p-3 font-semibold text-white">Payment routing information (creators)</td>
                    <td className="p-3">Pay out earnings</td>
                    <td className="p-3">Contract / Legal obligation</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">4. Retention Schedule</h3>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Account data:</strong> While active, plus 7 Days after deletion.</li>
              <li><strong className="text-white">Server text messages:</strong> Retained until deleted by You, Server admins, Account deletion + 7 days.</li>
              <li><strong className="text-white">Direct messages:</strong> Retained Until Account Deletion + 7 Days.</li>
              <li><strong className="text-white">Call signaling logs:</strong> Retained for 7 Days.</li>
              <li><strong className="text-white">Uploaded music/video:</strong> While active and published, plus 14 days after removal from the app.</li>
              <li><strong className="text-white">Play/watch history & royalty records:</strong> 7 years, for financial record-keeping.</li>
              <li><strong className="text-white">App telemetry:</strong> 30 days unless user does not consent.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">5. Strict Data Care Mode</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Mesh features a "Strict Data Care" mode in Account Settings. When toggled ON:
            </p>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li>Non-essential application state logs are routinely purged.</li>
              <li>Your session telemetry is anonymized.</li>
              <li>Your Discover recommendations rely on on-device processing rather than cloud profiling.</li>
            </ul>
            <p className="text-[#888] leading-relaxed mb-4">
              With Strict Data Care OFF, recommendations use algorithmic curation based on your listening/watching history and telemetry.
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">6. Data Hosting & International Transfers</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              We do not sell your personal data to advertisers. We share data only with trusted service providers, strictly to run Mesh, including Supabase (database hosting), WebRTC infrastructure/TURN-STUN providers, and Stripe Billing. Our database is hosted by Supabase in the eu-west-1 region (Ireland), within the European Economic Area (EEA). For UK users, this means your data is transferred from the UK to the EEA. The UK government treats all EEA member states as adequate jurisdictions, so this transfer takes place without needing additional safeguards. 
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">7. UK GDPR Rights & Age Requirements</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Under the UK GDPR, you have the right to Access, Rectify, Erase, Restrict, Object to processing, Data portability, and Withdraw consent. You can manage this directly in Account Settings or contact Legal@meshservicesuk.com. You can lodge a complaint with the UK Information Commissioner's Office (ICO) at ico.org.uk or 0303 123 1113. Mesh is intended for users 18 and over in the UK, Ireland, Germany, Netherlands, France, and Spain.
            </p>
          </section>

          {/* Section: US Privacy Policy */}
          <section id="privacy-us" className="mb-16 scroll-mt-32">
            <div className="flex items-center gap-2 mb-6 border-b border-white/10 pb-4">
              <Lock className="w-5 h-5 text-[#3b1df2]" />
              <h2 className="text-2xl font-bold text-white">US Privacy Policy</h2>
            </div>
            <p className="text-xs text-[#888] uppercase tracking-wider mb-6">Effective Date: 10/08/2026</p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">1. Who We Are & Infrastructure Location</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Mesh is operated by Mesh Services US Provided by Dylan Scully. For users in the United States, your data is securely stored on our infrastructure hosted by Supabase in the US-WEST-1 region (Northern California). You can contact us about privacy at meshuslegal@meshservicesuk.info.
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">2. Data Practices & COPPA Compliance</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              We collect data to operate servers, connect voice calls via WebRTC (we do not receive, transmit through, record, or store the audio), deliver private messages, and calculate creator royalties. Mesh is strictly intended for users 18 and over, and we will utilize age-verification systems during onboarding to restrict access to anyone under 18.
            </p>
            <p className="text-[#888] leading-relaxed mb-4">
              Mesh features a "Strict Data Care" mode where non-essential application state logs are routinely purged, your session telemetry is anonymized, and your Discover recommendations rely on on-device processing rather than cloud profiling.
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">3. US State Privacy Rights (CCPA/CPRA)</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Under the California Consumer Privacy Act (CCPA) and California Privacy Rights Act (CPRA), as well as applicable privacy laws in other US states, you have the right to:
            </p>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Access/Know:</strong> Request disclosure of the specific pieces and categories of personal information we have collected about you.</li>
              <li><strong className="text-white">Delete:</strong> Request the deletion of your personal data.</li>
              <li><strong className="text-white">Correct:</strong> Request correction of inaccurate personal data.</li>
              <li><strong className="text-white">Opt-out of Sale or Sharing:</strong> We do not sell your personal data to advertisers.</li>
              <li><strong className="text-white">Non-Discrimination:</strong> Receive equal service and pricing regardless of exercising your privacy rights.</li>
            </ul>
            <p className="text-[#888] leading-relaxed mb-4">
              Manage most of this directly via our CCPA-aligned data export/delete tooling in Account Settings, or contact meshuslegal@meshservicesuk.info.
            </p>
          </section>

          {/* Section: DMCA & Copyright Policy */}
          <section id="dmca" className="mb-16 scroll-mt-32">
            <div className="flex items-center gap-2 mb-6 border-b border-white/10 pb-4">
              <FileText className="w-5 h-5 text-[#3b1df2]" />
              <h2 className="text-2xl font-bold text-white">DMCA & Copyright Policy</h2>
            </div>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">1. Compliance</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Mesh respects intellectual property rights and complies with the US Digital Millennium Copyright Act (DMCA), UK Copyright, Designs and Patents Act 1988, and EU Copyright regulations. We respond to valid notices of alleged copyright infringement under the Digital Millennium Copyright Act (DMCA).
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">2. Submitting Takedown Notices</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              To lodge a notice of claimed infringement, send a written communication including: identification of the copyrighted work, exact URLs/locations of infringing material, full contact information, and sworn good-faith statements to:
            </p>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-1 mb-4">
              <li>UK/EU Agent Email: <a href="mailto:Legal@meshservicesuk.com" className="text-[#3b1df2] underline">Legal@meshservicesuk.com</a></li>
              <li>US Agent Email: <a href="mailto:meshuslegal@meshservicesuk.info" className="text-[#3b1df2] underline">meshuslegal@meshservicesuk.info</a></li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">3. Repeat Infringer Policy</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Mesh enforces a strict three-strike policy. Accounts that repeatedly infringe copyright will have creator access terminated and media permanently removed from Mesh Music and Mesh TV.
            </p>
          </section>

          {/* Section: Community Guidelines */}
          <section id="community" className="mb-16 scroll-mt-32">
            <div className="flex items-center gap-2 mb-6 border-b border-white/10 pb-4">
              <Users className="w-5 h-5 text-[#3b1df2]" />
              <h2 className="text-2xl font-bold text-white">Community Guidelines</h2>
            </div>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">1. Zero Tolerance Rules</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              The following behaviors result in an immediate, permanent network ban:
            </p>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Hate Speech & Discrimination:</strong> Slurs, targeted attacks, or bigotry based on protected characteristics.</li>
              <li><strong className="text-white">Illegal Content & CSAM:</strong> Transmission of illegal material or child exploitation content (reported directly to law enforcement).</li>
              <li><strong className="text-white">Doxxing & Harassment:</strong> Releasing private personal data or conducting targeted harassment in text channels, DMs, or voice calls.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">2. Messaging & Moderation</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Server admins possess moderation rights over text channels within their respective servers. Users may enable "Quarantine DMs" in account settings to filter links from non-friends. Violations can be reported directly via in-app reporting tools.
            </p>
          </section>

          {/* Section: Mesh TV Terms of Use */}
          <section id="mesh-tv" className="mb-16 scroll-mt-32">
            <div className="flex items-center gap-2 mb-6 border-b border-white/10 pb-4">
              <Tv className="w-5 h-5 text-[#3b1df2]" />
              <h2 className="text-2xl font-bold text-white">Mesh TV Terms of Use</h2>
            </div>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">1. The Service</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Each time you visit, browse, or use the Mesh TV service, you accept this Agreement on behalf of yourself and all members of your household and others who use the service under your account. Mesh TV is a personalized service that offers, recommends, and helps you discover digital movies, television shows, and other video content ("Digital Content"). We personalize content and features, including showing you recommendations that might be of interest to you.
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">2. Compatible Devices & Geographic Variability</h3>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li>In order to stream or download Digital Content, you will need to use a personal computer, portable media player, or other device that meets our system and compatibility requirements.</li>
              <li>The Digital Content available to you will vary over time and by location due to technical and other restrictions imposed by content providers.</li>
              <li>We will use technologies to verify your geographic location, and you may not use any technology or technique to obscure or disguise your location.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">3. Digital Content & Restrictions</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              The Service may allow you to access Digital Content on a subscription basis (such as through Mesh TV Pro), as well as through rentals, purchases, pay-per-view, or on a free ad-supported basis. Subject to your payment and compliance with these terms, you are granted a non-exclusive, non-transferable, non-sublicensable, limited license to access and view the Digital Content for personal, non-commercial, private use.
            </p>
            <p className="text-[#888] leading-relaxed mb-4">
              You may not copy, display, sell, rent, or broadcast the Digital Content. You are also strictly prohibited from attempting to bypass or circumvent any digital rights management or content protection system used as part of Mesh TV.
            </p>
            <p className="text-[#888] leading-relaxed mb-4">
              The resolution and quality of the Digital Content depend on your device and bandwidth, and we may decrease the resolution of streamed content to provide an uninterrupted viewing experience.
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">4. Liability & Additional Terms</h3>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Software and Data:</strong> The Mesh TV Service and Software may provide us with information relating to your use, including the Digital Content that you download and stream, and your viewing history. We may provide certain information regarding your use of Digital Content to video content providers in a manner that is not identifiable to you.</li>
              <li><strong className="text-white">Termination:</strong> We may terminate your access to Mesh TV or Mesh TV Pro at our discretion. If we do so without cause, we will give you a pro-rated refund; however, if you violate any terms of this Agreement, your rights terminate immediately without a refund.</li>
              <li><strong className="text-white">Explicit Content:</strong> You may encounter content that may be offensive or explicit, and you agree to use the Service at your sole risk.</li>
              <li><strong className="text-white">Modifications:</strong> We may modify the Service to improve functionality, maintain quality, or for legal and security reasons. If you are in the EU or UK and the changes materially and adversely impact usability, we will notify you at least 30 days in advance, giving you the right to cancel and receive a prorated refund.</li>
              <li><strong className="text-white">Limitation of Liability:</strong> In no event shall our total liability to you for damages arising from your use of the Service or Digital Content exceed the amount you paid to us over the past 12 months to purchase, rent, or view the Digital Content related to your claim.</li>
            </ul>
          </section>

          {/* Section: Paid Subscriptions & Mesh TV Pro */}
          <section id="subscriptions" className="mb-16 scroll-mt-32">
            <div className="flex items-center gap-2 mb-6 border-b border-white/10 pb-4">
              <CreditCard className="w-5 h-5 text-[#3b1df2]" />
              <h2 className="text-2xl font-bold text-white">Mesh+ Paid Subscription</h2>
            </div>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">1. Provider & Eligibility</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              The Mesh entity providing the service corresponds to where you live: if you live in the United Kingdom, services are provided by Mesh Services UK Ran by Dylan Scully; if you live in the European Union, services are provided by our EU hub; and if you live in the United States, services are provided by our US subsidiary. You must be at least 18 years old (or the age of legal majority in your jurisdiction) to purchase a Paid Subscription, and a valid debit/credit card is required.
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">2. Billing & Auto-Renewal</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Mesh+ is offered on an auto-renewing subscription basis. By subscribing, you authorise Mesh to charge your selected payment method on a recurring Monthly (£4.99) or Annual (£49.99) billing cycle. All prices are listed in Great British Pounds (GBP/£) and are inclusive of UK Value Added Tax (VAT) where applicable.
            </p>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Auto-Renewal:</strong> Your Subscription will automatically renew at the end of each billing cycle unless you cancel it before the renewal date.</li>
              <li><strong className="text-white">Reminders:</strong> For Annual subscriptions, we will send you a written reminder notice via email before your Subscription auto-renews, detailing the renewal date and upcoming charges.</li>
              <li><strong className="text-white">Promotions:</strong> If you activate a Promotional Offer for a Paid Subscription, you will automatically be moved to the full-price subscription (£4.99/mo or £49.99/yr) at the end of the promotional period. You must cancel your Promotional Offer before it expires if you do not wish to be charged.</li>
              <li><strong className="text-white">Price Changes:</strong> Mesh reserves the right to change the price of the Mesh+ Subscription. If we increase the price, we will provide you with at least thirty (30) days' written notice before the change takes effect. Price changes take effect at the start of the next subscription period.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">3. Cancellations & Terminations</h3>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Cancellation Guide:</strong> To cancel your Mesh+ Subscription Head to the Customer Portal page and cancel the subscription, Please be aware that we do not store your payment information, This is all handled securely by our payment processor "Stripe".</li>
              <li><strong className="text-white">Mesh Rights:</strong>  Mesh reserves the right to suspend, discontinue, or terminate your access to Paid Subscriptions at any time without refund if you violate our Community Conduct rules (e.g., sharing illegal content, harassment, copyright infringement on Mesh Music/TV), if required by a court or regulatory authority, or to protect the security of our WebRTC or database infrastructure.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">4. UK/EU Statutory Rights & Cooling-Off Periods</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Under UK consumer protection law, you have a statutory right to cancel your Subscription within 14 days of purchase and receive a full refund.
            </p>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Prorated Refunds:</strong> Mesh subscriptions are digital services, and if you cancel during the 14-day window, you will receive a partial refund prorated based on how many days of use you enjoyed before cancelling.</li>
              <li><strong className="text-white">The Digital Waiver:</strong> By choosing to stream, download, or access Mesh+ exclusive content within the first 14 days of your Subscription, you expressly consent to the immediate performance of the contract and acknowledge that you will lose your 14-day right to cancel and receive a refund. Unused Subscriptions retain the right to claim a full refund within the 14-day window.</li>
              <li><strong className="text-white">Annual Renewal Cooling-Off Right:</strong> In compliance with the DMCCA, if you are on an Annual Subscription (£49.99/year), you are entitled to a secondary 14-day cooling-off period immediately following the auto-renewal of your contract. If you cancel within this 14-day renewal window, you are entitled to a refund for the renewed year, adjusted proportionally for any content consumed during those 14 days.</li>
              <li><strong className="text-white">Trial Conversions:</strong> If you live in the UK, a new 14-day Cancellation Period applies when a free trial converts to a full Paid Subscription.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">5. Arbitration & Local Jurisdictions</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              If you live in the United States, you are bound by the arbitration provision set forth in the Mesh Terms of Service, meaning disputes will be resolved by mandatory binding arbitration, and you waive any right to participate in a class action lawsuit or class-wide arbitration.
            </p>
            <p className="text-[#888] leading-relaxed mb-4">
              Pursuant to the Code de la Consommation, users in France are entitled to consumer mediation to resolve disputes. For users in Germany and the Netherlands, nothing in these Terms affects your legal rights under mandatory local laws regarding digital products, digital services, and general terms and conditions.
            </p>
          </section>

              <section id="MeshAI" className="mb-16 scroll-mt-32">
            <div className="flex items-center gap-2 mb-6 border-b border-white/10 pb-4">
              <CreditCard className="w-5 h-5 text-[#3b1df2]" />
              <h2 className="text-2xl font-bold text-white">Mesh AI Policies</h2>
            </div>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">Scope and Acceptance</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              This Policy Applies to all Mesh+ Subscribers and users interacting with Mesh AI Features.
            </p>
            <p className="text-[#888] leading-relaxed mb-4">
              Usage of Mesh AI is subject to Mesh' Terms of Service and Privacy Policy.
            </p>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">Mesh AI Acceptable Use Policy</h3>
            <p className="text-[#888] leading-relaxed mb-4">
              Mesh AI is Designed to enchane community collaboration, moderation and communication. You agree not to use Mesh AI to: 
            </p>
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Generate Harmful Content:</strong> Create hate speech, harrasment, explicit content, threats of violence, or content that promotes illegal activities.</li>
              <li><strong className="text-white">Malicious Activities:</strong>  Generate phising materials, spam, malware code, or attempt to bypass platform security measures.</li>
              <li><strong className="text-white">Impersonation :</strong> Misrepresent AI-generated outputs as direct human statements intended to deceive others, or impersonate real individuals.</li>
              <li><strong className="text-white">Data Scraping & Extraction:</strong> Attempt to extract underlying system prompts, model weights, or unauthorized proprietary server data via prompt injection attacks.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">Data Privacy and RAG Indexing</h3>
           
            <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Server Context & RAG:</strong> Features like server knowledge search utilize Retrieval-Augmented Generation (RAG) to index channel histories and pinned documents. Server administrators control what channels are indexable.</li>
              <li><strong className="text-white">Data Handling:</strong> Mesh processes queries through secure third-party foundation model APIs. We do not use your private communications or personal chat prompts to train public AI models.</li>
              <li><strong className="text-white">User Responsibility:</strong> Do not input highly sensitive Personally Identifiable Information (PII), financial details, or credentials into public or open server channels where Mesh AI has access.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">Disclaimers and Limitations of Liability</h3>
             <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">AI Hallucinations:</strong> Mesh AI is powered by large language models that may occasionally produce inaccurate, incomplete, or biased information ("hallucinations").</li>
              <li><strong className="text-white">No Professional Advice:</strong> Responses generated by Mesh AI do not constitute legal, medical, financial, or professional advice. Always verify critical information against official server documents or human moderators.</li>
              <li><strong className="text-white">As-Is Availability:</strong> Mesh AI is provided on an "as-is" and "as-available" basis. Mesh makes no guarantees regarding uninterrupted uptime, response speed, or absolute accuracy of generated summaries.</li>
              <li><strong className="text-white">Mesh AI is in Active Development</strong> Mesh AI is continuously evolving, and its capabilities and performance may change over time.</li>
            </ul>

            <h3 className="text-lg font-bold text-white mt-6 mb-2">Mesh+ Subscription & Fair Use Limits</h3>
             <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Subscription Requirement:</strong> Access to Mesh AI is an exclusive perk of an active mesh+ subscription. Downgrading or canceling your subscription will immediately revoke access to Mesh AI features.</li>
              <li><strong className="text-white">Rate Limits & Fair Use:</strong> Mesh AI is subject to rate limits and fair use policies to ensure equitable access for all users. Excessive usage may result in temporary restrictions.</li>
            </ul>

               <h3 className="text-lg font-bold text-white mt-6 mb-2">Policy Violations</h3>
               <p className="text-[#888] leading-relaxed mb-4">
              Failure to comply with this Mesh AI user Policy May Result in: 
            </p>
             <ul className="list-disc list-outside ml-5 text-[#888] space-y-2 mb-4">
              <li><strong className="text-white">Temporary or permanent restriction of Mesh AI features.</strong> </li>
              <li><strong className="text-white">Suspension or termination of your mesh+ subscription and/or Mesh user account.</strong></li>
              <li><strong className="text-white">Reporting of severe violations to relevant legal authorities if unlawful activity is detected.</strong></li>
            </ul>
            <p className="text-[#888] leading-relaxed mb-4">
              If you believe we have got it wrong contact us at <a href="mailto:support@meshservicesuk.com" className="text-[#3b1df2] underline">support@meshservicesuk.com</a>
            </p>  
          </section>

        </div>
      </main>
       <footer className="border-t border-white/5 mt-20 pt-10 pb-6">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="text-zinc-600 font-medium text-sm text-center md:text-left">
            © {new Date().getFullYear()} Mesh Services UK. <br className="md:hidden" />
            <span className="hidden md:inline"> | </span> 
            Run with purpose by Dylan Scully.
          </div>
          <div className="flex flex-wrap justify-center gap-6 text-sm font-medium text-zinc-500">
            <Link to="/bot" className="hover:text-zinc-200 transition-colors">Discord Bot</Link>
            <Link to="/policies" className="hover:text-zinc-200 transition-colors">Terms & Privacy</Link>
            <Link to="/policies" className="hover:text-zinc-200 transition-colors">DMCA</Link>
            <Link to="/support" className="hover:text-zinc-200 transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}